Fix setting the effect
Setting the effect causes this error to be thrown:

```
ReferenceError: Can't find variable: details
```

This because that variable is not declared within that function.